### ISSUE TITLE
Rendering issues while trying to add Bio Info in

### ISSUE THREAD

**Issue by chomweaver** [SAEL-SWFSC/PAM-SI-Mtg-March2024#1]
When I added my bio info into the AttendeeIntros.qmd, I keep getting rendering issues when pushing the info from GitHub Desktop. Not sure what is happening. May need to look at yml?

**Comment by shannonrankin** [comment]
The render issue is with github pages, so it does not show up as an HTML:
_ERROR: Unable to publish to GitHub Pages (the remote origin does not have a branch named "gh-pages". Use first `quarto publish gh-pages` locally to initialize the remote repository for publishing.)_

However, the docx output worked well (if you render locally, you can see the compiled document in the docs folder.
**CORY---** Note: Your picture is upside down!

I was working on trying to fix the html render the other day, to no success. It apparently cannot find the index.html, but when I moved it, it also did not work. It could be a  yml issue, but I do not yet know how to fix that. 

_**Note**: Repo expects the index.html to be in either the root directory or the docs folder (see Pages section under Settings), but this repo was based on a Tech Memo template made by Eli Holmes, and the index.html is stored in a _site folder (not sure why). When I tried moving the index.html folder to either the root or docs folder, it still did not fix the situation. I need to do more homework on this, and then reach out to Eli Holmes to better understand how this works._ 

Here are my suggestions to mitigate this problem: 

- [ ] Add a note on the Open Sciences page that: _We are aware of an issue rendering to HTML and are working on a solution. If you follow these directions, your update will be made to the docx file (in the docs folder).
- [ ] Address the issue of rendering to HTML

If you have other thoughts/suggestions, please let me know.

**Comment by shannonrankin** [comment]
Closing this issues as the HTML issues has been opened as an independent issue
