### ISSUE TITLE
Report Acknowledgements

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#11]
Create and draft Acknowledgements document, following instructions outlined [here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Acknowledge.html). 

- [ ] Query Attendees using Github Discussions
- [ ] Create Acknowledgements file
- [ ] Add names of all attendees
- [ ] Add any acknowledgements suggested by attendees
- [ ] Commit & Push to Github
- [ ] Enter comments below on what was completed, and any problems or questions encountere. Reassign issue to Becca and Sofie

**Comment by cberchok** [comment]
Do I also need to comment here, if I included a comment when I pushed this up??

**Comment by rebecca-vanhoeck** [comment]
Its not required, but still helpful so I know who made edits in case I have questions. Thanks Catherine!
