### ISSUE TITLE
Add me to repository

### ISSUE THREAD

**Issue by rebecca-vanhoeck** [SAEL-SWFSC/PAM-SI-Mtg-March2024#16]
email: rebecca.vanhoeck@noaa.gov; username: rebecca-vanhoeck

I think I made a local project before requesting to join the repository, so I'm not able to commit changes yet or update my bio.

**Comment by Kourtney-Burger** [comment]
Hey Becca, I added you as an admin. Let me know if that resolves your issue!

**Comment by rebecca-vanhoeck** [comment]
Thanks Kourtney! I made a rookie mistake and made changes without actually opening the R project so they weren't showing up in my git window.
