### ISSUE TITLE
How do I add myself to this repository?

### ISSUE THREAD

**Issue by sofievanparijs** [SAEL-SWFSC/PAM-SI-Mtg-March2024#20]
Good morning! First time on Github and I tried to look up how to join but it doesn't work. Does Shannon need to add me? Am feeling very stupid.... 
Thank you!
Sofie

**Comment by sofievanparijs** [comment]
Thank you Becca!

**Comment by rebecca-vanhoeck** [comment]
Hi Sofie! You did exactly the right thing to be added to the repo.
