### ISSUE TITLE
Report- NCEI Summary

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#21]
Create Workshop Report Section for NCEI Archiving Summary, following directions in Exercise (more details[ here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-NCEI.html)):

- [x] Create PAM-SI-Mtg-Exercises-NCEI.qmd in Meeting Repo
- [x] Add Names of Section Leads (in bold)
- [x] Link this qmd to the quarto.yml
- [x] Commit & Push to Github
- [x] Mark all of these as completed (check boxes)
- [x] Reassign this project to the Section leads and comment on this thread what you completed, and any questions/comments you have, then save your comment. 
- [x] Finalize the "Priority Project" tables from the [draft workshop report section](https://docs.google.com/document/d/1JDcJC8RgReVsdq1XeOSxvBY76jwXI6KKTEE00kEM9K0/edit?usp=drive_link). Do not worry about formatting because the content will be copied to RStudio
- [x] Copy the information from the tables in draft workshop report section into the NCEI.qmd file 
- [x] Commit & Push to Github
- [x] Check boxes as completed and reassign the issue to Becca

**Comment by rebecca-vanhoeck** [comment]
Hi @carriecwall and @jgedamke! I'm following up on the NCEI Archiving Round Table to ask that you review and finalize the draft report section by Monday 4/1. Please do not worry about editing the Discussion Notes section, those can be left as is in the google doc. I have added a few action items to the list above to help track the progress. Please let me know if you have any trouble with the gmd file or github! Thank you!

**Comment by carriecwall** [comment]
@rebecca-vanhoeck Tasks completed as requested. Two tables have been provided in the ncei.qmd file. The top table is specific and relevant to this task. Task team members haven't been specifically called out as it's essentially everyone but would perhaps be best to update after POCs are identified in the new spreadsheet? The bottom table captures a part of the discussion that occurred during the breakout but isn't relevant to NCEI archiving. I wanted to document it but haven't identified a lead or team associated with the actions. This could be a good/better fit for the "software" group.

**Comment by rebecca-vanhoeck** [comment]
Thanks, Carrie! This looks great, I made a few minor changes to the text (adding project titles, refining the target outcome, and formatting the subtasks). Ultimately moving project 2 to the software group is likely a good idea. I'm going to keep it where it is for now, and then we can discuss that when we review the report at the SI meeting on Wednesday. I'm going to close this issue since the qmd is updated.
