### ISSUE TITLE
Report- Cloud Section

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#26]
Create Workshop Report Section for Cloud Summary, following directions in Exercise (more details [here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Cloud.html)):

- [x]  Create PAM-SI-Mtg-Exercises-Cloud.qmd in Meeting Repo
- [x]  Add Names of Section Leads (in bold)
- [x]  Link this qmd to the quarto.yml
- [x]  Commit & Push to Github
- [x]  Mark all of these as completed (check boxes)
- [x]  Reassign this project to the Section leads and comment on this thread what you completed, and any questions/comments you have, then save your comment.
- [x] Finalize the "Priority Project" tables from the [draft workshop report section](https://docs.google.com/document/d/17pZu3LdDwY9VjbTR4QxtGJQ-RlRgXISOUSgNzvg98Pw/edit?usp=drive_link). Do not worry about formatting because the content will be copied to RStudio
- [x] Copy the information from the tables in draft workshop report section into the Cloud.qmd file
- [x] Commit & Push to Github
- [x] Check boxes as completed and reassign the issue to Becca

**Comment by rebecca-vanhoeck** [comment]
Hi @sofievanparijs and @DanWoodrichNOAA! I'm following up on the Cloud Computing Round Table to ask that you review and finalize the draft report section by Monday 4/1. Please do not worry about editing the Discussion Notes section, those can be left as is in the google doc. I have added a few action items to the list above to help track the progress. Please let me know if you have any trouble with the gmd file or github! Thank you!

**Comment by sofievanparijs** [comment]
Thanks ! I will tidy this up probably tomorrow and do the Management section too. Will definitely be done by end of week!

**Comment by sofievanparijs** [comment]
@rebecca-vanhoeck @DanWoodrichNOAA - cleaned up the google docs link is here: https://docs.google.com/document/d/17pZu3LdDwY9VjbTR4QxtGJQ-RlRgXISOUSgNzvg98Pw/edit

**Comment by rebecca-vanhoeck** [comment]
Thank you both! I've transferred everything to the github file and pushed the changes. Closing this issue now that the section is completed.
