### ISSUE TITLE
Report-Detection Section

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#27]
Create Workshop Report Section for Detection Summary, following directions in Exercise (more details [here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Detection.html)):

- [x]  Create PAM-SI-Mtg-Exercises-Detection.qmd in Meeting Repo
- [x]  Add Names of Section Leads (in bold)
- [x]  Link this qmd to the quarto.yml
- [x]  Commit & Push to Github
- [x]  Mark all of these as completed (check boxes)
- [x]  Reassign this project to the Section leads and comment on this thread what you completed, and any questions/comments you have, then save your comment.
- [ ] Finalize the "Priority Project" tables from the [draft workshop report section](https://docs.google.com/document/d/1SCds3MX9us_kDyvNLZQcCA2Isgtp3z9ZfoU8TLQeMXQ/edit?usp=drive_link). Do not worry about formatting because the content will be copied to RStudio
- [x] Copy the information from the tables in draft workshop report section into the Detection.qmd file
- [ ] Commit & Push to Github
- [ ] Check boxes as completed and reassign the issue to Becca

**Comment by rebecca-vanhoeck** [comment]
Hi @namariD and @TaikiSan21! I'm following up on the Acoustic Detection Software Round Table to ask that you review and finalize the draft report section by Monday 4/1. Please do not worry about editing the Discussion Notes section, those can be left as is in the google doc. I have added a few action items to the list above to help track the progress. Please let me know if you have any trouble with the gmd file or github! Thank you!

**Comment by namariD** [comment]
Hi @TaikiSan21 @rebecca-vanhoeck I just created a new qmd file and pushed it to GitHub that is the barebones of our table just to test to see if I did it right. File is called PAM-SI-Mtg-Exercises-DetectionSection.qmd. Feedback from you is requested as I'm not sure if I did things right. If so, I'll continue tweaking the document.

**Comment by rebecca-vanhoeck** [comment]
Hi Annamaria! Thanks for testing, the file looks great! The only thing is that I renamed the file as "Detection.qmd" so that it is properly associated with the yaml file that renders the whole report together.

**Comment by namariD** [comment]
Glad to hear. @TaikiSan21 please add anything else to the document as you see fit. I'll take a look at it again on Friday

**Comment by TaikiSan21** [comment]
@namariD just made and pushed some minor edits, thanks for handling the initial transfer!

**Comment by rebecca-vanhoeck** [comment]
Thank you both! I'm closing this issue now that the Detection info is all copied over and looks great!
