### ISSUE TITLE
Report- Github Section

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#28]
Create Workshop Report Section for Github Summary, following directions in Exercise (more details [here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Github.html)):

- [x] #72
- [x]  Add Names of Section Leads (in bold)
- [x]  Link this qmd to the quarto.yml
- [x]  Commit & Push to Github
- [x]  Mark all of these as completed (check boxes)
- [x]  Reassign this project to the Section leads and comment on this thread what you completed, and any questions/comments you have, then save your comment.
- [x] Finalize the "Priority Project" tables from the [draft workshop report section](https://docs.google.com/document/d/1JJhZeJujJ2tMbODDSARREBBwJzUe6pVTL2XTOlvHZMQ/edit?usp=drive_link). Do not worry about formatting because the content will be copied to RStudio
- [x] Copy the information from the tables in draft workshop report section into the Github.qmd file
- [x] Commit & Push to Github
- [x] Check boxes as completed and reassign the issue to Becca

**Comment by DanWoodrichNOAA** [comment]
Pushed changes on branch 'github' @Kourtney-Burger @MelissaSoldevilla

**Comment by rebecca-vanhoeck** [comment]
Hi Shannon! I'm connecting with all Round Table leads on their issue to ask that the draft workshop report sections are reviewed and finalized by Monday 4/1. Since we led this conversation together, I can take the lead on editing the report summary this week and will comment here once I've finished so you can review it. Thanks!

**Comment by shannonrankin** [comment]
Thank you-- I will be offline next week (family camping for spring break!).
Happy to review the following week when I return, please tag me at that
time.

**Comment by rebecca-vanhoeck** [comment]
I've finished the GitHub summary [here](https://docs.google.com/document/d/1JJhZeJujJ2tMbODDSARREBBwJzUe6pVTL2XTOlvHZMQ/edit?usp=sharing). If you have time to review before heading out on spring break, great, but no worries if not! I will likely include it as is in the draft workshop report to share with the SI working group next week but can always make edits once you're back.

**Comment by rebecca-vanhoeck** [comment]
Thanks, shannon! I revised the summary based on your comments and pushed the changes to github. Closing this issue now, so I can track which sections are completed.
