### ISSUE TITLE
Report- Management Section

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#29]
Create Workshop Report Section for Management Summary, following directions in Exercise (more details [here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Management.html)):

- [x]  Create PAM-SI-Mtg-Exercises-Management.qmd in Meeting Repo
- [x]  Add Names of Section Leads (in bold)
- [x]  Link this qmd to the quarto.yml
- [x]  Commit & Push to Github
- [x]  Mark all of these as completed (check boxes)
- [x]  Reassign this project to the Section leads and comment on this thread what you completed, and any questions/comments you have, then save your comment.

**Comment by rebecca-vanhoeck** [comment]
Section has been updated and pushed to Git! Closing this issue now.
