### ISSUE TITLE
Add me to Repository

### ISSUE THREAD

**Issue by namariD** [SAEL-SWFSC/PAM-SI-Mtg-March2024#33]
Annamaria DeAngelis
annamaria.deangelis@noaa.gov
namariD
@shannonrankin @Kourtney-Burger @rebecca-vanhoeck

**Comment by namariD** [comment]
The gear icons are not visible to me on the right panel under any of the sections

**Comment by rebecca-vanhoeck** [comment]
I've added you to the repository! Thanks for letting us know that the gear icon isn't visible.

**Comment by namariD** [comment]
They're visible now!
