### ISSUE TITLE
Add me to Repository

### ISSUE THREAD

**Issue by jlkeating** [SAEL-SWFSC/PAM-SI-Mtg-March2024#38]
Jennifer McCullough
jennifer.mccullough@noaa.gov
jlkeating

**Comment by shannonrankin** [comment]
Hello Jennifer--You have been added as an admin to this repository. Please move forward with the rest of the pre-meeting prep and let us know if you have any questions!

**Comment by shannonrankin** [comment]
Added to repo & completed
