### ISSUE TITLE
Some attendee bios were deleted

### ISSUE THREAD

**Issue by rebecca-vanhoeck** [SAEL-SWFSC/PAM-SI-Mtg-March2024#39]
The example formatting, Marla and Manolo's bios were accidentally deleted. I'm pretty sure there is a way to go back into the history and recover their bios, but I'm not confident in how to do it, so I'm creating an issue instead. Thanks!

**Comment by shannonrankin** [comment]
Shannon Replaced these, so they should all be there (at the least, the bios match the images)
