### ISSUE TITLE
WIFI Instructions/IT Help

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#4]
- [ ] Print instructions for WIFI 
 - [ ] Check in with IT re: help first morning
 - [ ] Other IT Prep?

**Comment by shannonrankin** [comment]
Becca-
@rebecca-vanhoeck 
I see you added a Google Meets-- is it for Multi-Day? If not, see pdf on previous comment for multi-day (let me know if you need help).
I added the WIFI info to the Agenda

If you've got the multi-day google meet all set up-- then you can close this- thanks!

**Comment by rebecca-vanhoeck** [comment]
Hi Shannon - yes it is a multi-day google meet. Thanks for adding the wifi info!
