### ISSUE TITLE
Ideas for tip of the day

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/PAM-SI-Mtg-March2024#42]
Placeholder for GitHub, Quarto, R, and open science [tips and tricks ideas ](https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024/discussions/categories/more-tips)

GitHub Tips
- [x] [Intro to issues](https://openscapes.github.io/series/core-lessons/github/github-issues.html#issues-in-the-wild)
- [x] github workflow, fetching from origin and opening in r studio
- [x] Referencing code/docs in issues
- [x] [fuzzy file finder](https://github.blog/2020-04-09-github-protips-tips-tricks-hacks-and-secrets-from-lee-reilly/#1-fuzzy-file-finder) 
- [x] Managing branches and how to reject some changes while pushing others

R Tips
- [x] [Big book of R](https://www.bigbookofr.com/) 

Open science tips
- [ ] [Make a pathway](https://openscapes.github.io/series/core-lessons/pathways.html), either individual or as a team (ideal)?
- [x] [here() package](https://here.r-lib.org/), [blog post](https://malco.io/articles/2018-11-05-why-should-i-use-the-here-package-when-i-m-already-using-projects)
- [x] joining/utilizing [open science communities](https://docs.google.com/presentation/d/1uMfh0ssHGDuJ9q8pcRk8-qIerkywE4X-E_KP4CiptKc/edit#slide=id.g23d8f62188b_2_189)
- [x] joining [bioacoustics stack exchange](https://bioacoustics.stackexchange.com)

**Comment by Kourtney-Burger** [comment]
Intro to issues? https://openscapes.github.io/series/core-lessons/github/github-issues.html#issues-in-the-wild

**Comment by Kourtney-Burger** [comment]
Referencing code/docs in issues?

**Comment by Kourtney-Burger** [comment]
github enterprise tip

**Comment by asimonis** [comment]
[How and why to make a research compendium](https://github.com/mbjoseph/intro-research-compendia)

[PSAW Github workshop](https://rverse-tutorials.github.io/PSAW-2022/git-part1.html)

**Comment by shannonrankin** [comment]
Here are some[ quarto tips of the day](https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/#category=website)

**Comment by Kourtney-Burger** [comment]
All of these have been added to the [tips and tricks discussions](https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024/discussions/categories/openscience-tips-tricks-and-resources)
