### ISSUE TITLE
Add me to Repository

### ISSUE THREAD

**Issue by cberchok** [SAEL-SWFSC/PAM-SI-Mtg-March2024#62]
Catherine Berchok
Catherine.Berchok@noaa.gov
cberchok

Okay - here is the issue - cberchok is registered until cberchok@yahoo.com, and I don't know how to make it switch to NOAA.

**Comment by shannonrankin** [comment]
Catherine--
You have been added as an admin to this repository. If the email matters in the future-- then we can figure it out later. Please move forward with the rest of the pre-meeting prep and let us know if you have any questions!  
Cheers,
Shannon
