### ISSUE TITLE
Add me to Repository

### ISSUE THREAD

**Issue by ludovictenorio** [SAEL-SWFSC/PAM-SI-Mtg-March2024#65]
Name: Ludo Tenorio
email: ludovic.tenorio@noaa.gov
Github: ludovictenorio
Github2: ludotenoaa

@shannonrankin 
@rebecca-vanhoeck
@Kourtney-Burger

**Comment by Kourtney-Burger** [comment]
Hi Ludo, I added both of your accounts to the repo!
