### ISSUE TITLE
Add me to Repository

### ISSUE THREAD

**Issue by MelissaSoldevilla** [SAEL-SWFSC/PAM-SI-Mtg-March2024#67]
Melissa Soldevilla
melissa.soldevilla@noaa.gov
MelissaSoldevilla
@shannonrankin
@rebecca-vanhoeck
@Kourtney-Burger

**Comment by ybarkley** [comment]
Hello Melissa!
You have been added as an admin to this repository. Please move forward with the rest of the pre-meeting prep and let us know if you have any questions!
