### ISSUE TITLE
Report Introduction

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/PAM-SI-Mtg-March2024#9]
Create and draft Acknowledgements document, following instructions outlined[ here](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-IntroText.html).

- [x] Create Intro.qmd
- [x] Add 'Background' paragraph from the PAM SI Vision Statement.docx
- [x] Copy the 2nd sentence from 'Project Tasks & Key Activities' from the PAM SI Proposal Revised Sept 18, 2023.docx
- [x] Add 'Proposal-Intro-Fig.jpg'. Provide the following caption: "Key Activities Identified by the Passive Acoustic Monitoring Strategic Initiative", and under 'Attributes' ID section, put 'Intro-diagram'.
- [x] Link Intro.qmd to _quarto.yml
- [x] Respond here on Github, add a comment stating what was done, and then re-assign to Becca and Sofie for final editing.

**Comment by Kourtney-Burger** [comment]
@rebecca-vanhoeck Shannon completed this section
